Added error message in case of incorrect credentials
DiaKEM/libre-link-up-api-client pull request #17
Opened 2023-05-26 16:05 UTC by Shawiizz

The current error we get when it's not the right credentials is this one: `TypeError: Cannot read properties of undefined (reading 'redirect')`

The new error message will help people to understand what's wrong (see https://github.com/DiaKEM/libre-link-up-api-client/issues/16 for more details.)

2023-05-26 18:50 UTC, khskekec requested changes
Thank you so much for your collaboration 🎉🎉🙏💪👍🎁🍻. Please allow me the following comment:

Could we Design the condition more strict to the "wrong credentials" error case then evaluating everything not equal to 200 as this case?

2023-05-29 14:47 UTC, Shawiizz commented
Yes you're right, it's better to only compare the case where it's only bad credentials if I understand what you asked me to do. I just discovered that I made a mistake in my code because I compared the wrong status code (`loginResponse.data.status` instead of `loginResponse.status`). 

After looking at the status code, when it fails because of bad credentials the `loginResponse.data.status` code equals to `2`. I'm making some changes, tells me if something should be changed :+1:

2023-05-29 15:06 UTC, khskekec commented
Thanks, looks great so far. You are the first contributor 😍❤️😘🎁

2023-05-29 15:06 UTC, merged

2023-05-29 15:20 UTC, Shawiizz commented
You're welcome, I'm glad I could contribute :)

2023-05-29 15:22 UTC, NzoSifou commented
Hi @khskekec,
Shawiizz is my friend and he helped me to make your API work for me, so I asked him if he could make a pull request to improve your API, because I'm not as good as him in typescript lol, so I would like to thank you for creating this API, it will help me to create my Android application for the management of my diabetes, it will greatly help me, so big thank you from France!

2023-05-29 22:57 UTC, khskekec commented
Hi @NzoSifou,

Glad to be able to help you so far. Best wishes from Germany and good luck for your Android project.